#!/bin/bash

set -ex

# create the .whl file in the ./dist folder
python -m build --installer pip --wheel
find ./dist/*.whl | xargs pip install 

curl -L "https://drive.usercontent.google.com/download?id=1sDLF3Nh4lOfg6j2tzJmaARpxCbkStnKd&confirm=xxx" -o examples/data/3_2_extract.mzML

# Download data from google drive
gdown --folder 1-RvQY14PLnY8sivldttT9v5inrz7uGLO -O ./examples/data/
