name: PASTAQ Many Linux PyPi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build wheels
        run: |
          git submodule init
          git submodule update --remote
          chmod +x pastaqwheels_p36-312.sh
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux_2_28_x86_64 /io/pastaqwheels_p36-312.sh

      - name: Upload wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m pip install --upgrade twine
          python3 -m pip install -U packaging
          ls -l
          ls -l ./wheelhouse/
          python3 -m twine upload ./wheelhouse/*
